name: Trigger auto deployment for cachetest1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app1 ]
    paths:
    - '**'
    - '.github/workflows/cachetest1-AutoDeployTrigger-e1baee76-5e7b-4c6a-b4ff-65f921ded353.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca9bdb5876bcacr.azurecr.io
          username: ${{ secrets.CACHETEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.CACHETEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca9bdb5876bcacr.azurecr.io/cachetest1:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CACHETEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cachetest1 -g container_apps --server ca9bdb5876bcacr.azurecr.io --username  ${{ secrets.CACHETEST1_REGISTRY_USERNAME }} --password ${{ secrets.CACHETEST1_REGISTRY_PASSWORD }}
            az containerapp update -n cachetest1 -g container_apps --image ca9bdb5876bcacr.azurecr.io/cachetest1:${{ github.sha }}
